class Randimg:
    # def check_Version(ua:bytes) -> bool: ...
    # def pc() -> str: ...
    # def mb() -> str: ...
    # def more_pc(n:int,format_:str) -> list: ...
    # def more_mb(n:int,format_:str) -> list: ...
    def process(self, ua: bytes, n: int, method: bytes) -> str | list: ...
